### ISSUE TITLE
Can I replace multiple links like tutorials-link in my cPanel?

### ISSUE THREAD

**Issue by NamVr** [WybeNetwork/VistaPanel-Customizations#10]
The title says it.

The best practice to optimize would be include all the js scripts into one one script.
Also we need to declare different `var`s or what?

**Comment by dimitrist19** [comment]
Yes. I can confirm that you can replace the tutorials link in cPanel. To change other links there are several ways you can do this. Can you tell me what link you are trying to change so maybe I can help?

**Comment by NamVr** [comment]
Yes I will tell you. But replacing links wont work in https -_-

**Comment by NamVr** [comment]
1. Getting Started
2. Backups
3. Free FTP Softwares
 atleast.

**Comment by dimitrist19** [comment]
> Yes I will tell you. But replacing links wont work in https -_-

I will notify PlanetCloud. He should be able to help you.

**Comment by NamVr** [comment]
Okay 🥇

**Comment by dimitrist19** [comment]
> 1. Getting Started
> 2. Backups
> 3. Free FTP Softwares
>    atleast.

Can you try this and tell me if it works?
```
<script>
function linkchange() {
  document.getElementById("item_backup_wizard").setAttribute("href", "Your link goes here");
  document.getElementById("icon-backup_wizard").setAttribute("href", "Your link goes here");
}
</script>
```
It should change the getting started link

**Comment by NamVr** [comment]
What should replace what?

**Comment by dimitrist19** [comment]
> What should replace what?

The code I sent should replace the Getting Started button. Place it in an ads section of cPanel.

**Comment by NamVr** [comment]
Are! That I know and understand. I am not a js dev bro.
I asked what is the replacing link and what is the replaced link?

**Comment by dimitrist19** [comment]
The replacing link is that you want to add and the replaced link is the page in the panel with the getting started guide. Just in the code where you see 'Your code goes here' replace it with your own link (e.g. https://exampledomain.com/gettingstartedguide).

Hope that I answered your question.

**Comment by NamVr** [comment]
I will try out soon and let you know.

**Comment by NamVr** [comment]
I added but.
It didn't worked -_-

**Comment by dimitrist19** [comment]
Yes. I know. That was the wrong code I had in my cPanel. The correct is locked in my files on my suspended domain. I think Anyx found a way to solve this. He will comment here soon

**Comment by 4yx** [comment]
Hi @NamVr,

Below is the code to replace Getting Started:

You will have to add two new variables, here I named them gi (getting started icon) and gt (getting started text), feel free to rename them to whatever you want.
`var gi = document.getElementById("icon-backup_wizard");`
`var gt = document.getElementById("item_backup_wizard"); `
to your `b` variable.

After that, you will have to add the following to your footer:
```
<script>
if (gi.hasAttribute("href")) {      
  gi.setAttribute("href", "your link goes here");
}
if (gt.hasAttribute("href")) {      
  gt.setAttribute("href", "your link goes here");
}
</script>
```
Feel free to try experimenting with adding them to the `b` variable you already have, whenever I tried that it never worked for me, so I had to set two different variables.

**Comment by 4yx** [comment]
Nevermind, just managed to get it to work under the same variable. New code will follow.

**Comment by 4yx** [comment]
Add these to your `b` variable:
```
gsitem: document.getElementById("item_backup_wizard"), 
gsicon: document.getElementById("icon-backup_wizard") 
```
And then add this script:
```
<script>
if (b.gsitem.hasAttribute("href")) {      
  gi.setAttribute("href", "your link goes here");
}
if (b.gsicon.hasAttribute("href")) {      
  gt.setAttribute("href", "your link goes here");
}
</script>
```
Replace ``your link goes here`` with your actual link, and you should be good to go!
I'm going to try and do the same for the other two as well, and will come back to you.

**Comment by 4yx** [comment]
Hello @NamVr,

I am done with all three items you requested. We will be releasing the script tomorrow alongside a tutorial on how to replace other links, too.

Add these to your ``b`` variable:
```
gsitem: document.getElementById("item_backup_wizard"), 
gsicon: document.getElementById("icon-backup_wizard"),
baicon: document.getElementById("icon-backup"),
baitem: document.getElementById("item_backup"),
fticon: document.getElementById("icon-ftp_connections"),
ftitem: document.getElementById("item_ftp_connections")
```

And after that, add this script:
```
<script type="text/javascript">
if (b.gsitem.hasAttribute("href")) {      
  b.gsitem.setAttribute("href", "your link goes here");
}
if (b.gsicon.hasAttribute("href")) {      
  b.gsicon.setAttribute("href", "your link goes here");
}
if (b.baicon.hasAttribute("href")) {      
  b.baicon.setAttribute("href", "your link goes here");
}
if (b.baitem.hasAttribute("href")) {      
  b.baitem.setAttribute("href", "your link goes here");
}
if (b.fticon.hasAttribute("href")) {      
  b.fticon.setAttribute("href", "your link goes here");
}
if (b.ftitem.hasAttribute("href")) {      
  b.ftitem.setAttribute("href", "your link goes here");
}
</script>
```

Replace `your link goes here` with the links you want to put for each one of them.

- `gsitem` and `gsicon` are "Getting Started"
- `baicon` and `baitem` are "Backups"
- `fticon` and `ftitem` are "Free FTP Software"

Feel free to ask us to reopen this ticket if it did not work, I tried it on my vPanel and it worked fine.

**Comment by 4yx** [comment]
Hello @NamVr,

I am done with all three items you requested. We will be releasing the script tomorrow alongside a tutorial on how to replace other links, too.

Add these to your ``b`` variable:
```
gsitem: document.getElementById("item_backup_wizard"), 
gsicon: document.getElementById("icon-backup_wizard"),
baicon: document.getElementById("icon-backup"),
baitem: document.getElementById("item_backup"),
fticon: document.getElementById("icon-ftp_connections"),
ftitem: document.getElementById("item_ftp_connections")
```

And after that, add this script:
```
<script type="text/javascript">
if (b.gsitem.hasAttribute("href")) {      
  b.gsitem.setAttribute("href", "your link goes here");
}
if (b.gsicon.hasAttribute("href")) {      
  b.gsicon.setAttribute("href", "your link goes here");
}
if (b.baicon.hasAttribute("href")) {      
  b.baicon.setAttribute("href", "your link goes here");
}
if (b.baitem.hasAttribute("href")) {      
  b.baitem.setAttribute("href", "your link goes here");
}
if (b.fticon.hasAttribute("href")) {      
  b.fticon.setAttribute("href", "your link goes here");
}
if (b.ftitem.hasAttribute("href")) {      
  b.ftitem.setAttribute("href", "your link goes here");
}
</script>
```

Replace `your link goes here` with the links you want to put for each one of them.

- `gsitem` and `gsicon` are "Getting Started"
- `baicon` and `baitem` are "Backups"
- `fticon` and `ftitem` are "Free FTP Software"

Feel free to ask us to reopen this issue if it did not work, I tried it on my vPanel and it worked fine.

**Comment by NamVr** [comment]
Sorry I can't understand the concept.
It is done twice for each requested things :( 
Also there is no references to outside script.

**Comment by mahofficial** [comment]
> Also there is no references to outside script.

Reference to the outside script is not necessary. You can write JS code in the advert area instead of referring to the outside script.

**Comment by NamVr** [comment]
Ok kindly close the issue here we will continue on Discord Ticket.
Thank You,
Kind regards.

**Comment by 4yx** [comment]
> We will be releasing the script tomorrow alongside a tutorial on how to replace other links, too.

Wow, I never realized we never got to do that. Should probably get this back on track.

**Comment by 4yx** [comment]
Sidenote: I believe early ideas of ways to implement this do not work, because we need to modify the elements in the PAGE.appGroups array for the URL changes to be reflected.

**Comment by 4yx** [comment]
This took me less than expected, anyway if nothing changes (which I hope) it can be considered complete.
