### ISSUE TITLE
Add a script that fixes the dropdown menu bug in vpanel

### ISSUE THREAD

**Issue by ItsGamingTube** [WybeNetwork/VistaPanel-Customizations#16]
So when you click on a button that redirect you to an another page (example you click on the change passwod button) the dropdown menu doesn't work anymore.

Pls make a script that fixes this bug

**Comment by mahofficial** [comment]
Kindly check the latest update made today.
Refer to the latest readme.md file for new code and instructions. Also, I linked the fix with this issue.

**Comment by mahofficial** [comment]
> So when you click on a button that redirect you to an another page (example you click on the change passwod button) the dropdown menu doesn't work anymore.

The dropdown menu of theme switcher is fixed. Are you referring to any other dropdown menu or what?
Can you explain it further.

**Comment by mahofficial** [comment]
![image](https://user-images.githubusercontent.com/25408054/123145644-7ccd7080-d476-11eb-8dd1-471e5434ca0b.png)
Refer to this image. I am on another page and dropdown of theme switcher is still working.

**Comment by ItsGamingTube** [comment]
Read my new thread

**Comment by ItsGamingTube** [comment]
> > So when you click on a button that redirect you to an another page (example you click on the change passwod button) the dropdown menu doesn't work anymore.
> 
> The dropdown menu of theme switcher is fixed. Are you referring to any other dropdown menu or what?
> Can you explain it further.
> 
> L.E: Kindly provide a complete detail like telling us the step to regenerate bug on our side, what exactly caused the error etc.

![image](https://user-images.githubusercontent.com/66141420/123152361-2c054a00-d46d-11eb-9cb1-294137f81054.png)

Make a script that fixes this bug.
When you open the dropdown menu (not the theme switcher) it doesn't open when you are on an another page (works only on the vpanel homepage)

**Comment by mahofficial** [comment]
I'll try, added on todo list

**Comment by 4yx** [comment]
I have a prototype ready, but the problem is that it makes the dropdown work everywhere except the home page where it was already working! Working on it and I'll hopefully have it listed here soon.

**Comment by 4yx** [comment]
@ItsGamingTube could you please confirm it's working on all pages as intended?
