### ISSUE TITLE
Tutorial changer not working

### ISSUE THREAD

**Issue by BastelPichi** [WybeNetwork/VistaPanel-Customizations#18]
Tried some of the stuff here, and i think its awesome! The only problem I have is that the tutorial Link changer does not work. I can see the source code in the explorer, but it does not do anything.

**Comment by 4yx** [comment]
> The problem is that DOMContentload triggers when the site itself is loaded - not when the site is really loaded(the time where theres this loading circle). That way it cant find the tutorial item and cant change its content.

That does not seem to be the issue. I tried putting it in the header advertising area (which loads after the loading circle is complete if I'm not mistaken), changed the DOMContentLoaded to a window.AddEventListener('load'), and I tried adding the script directly in the head and body areas.
The best result I got was the tutorial link changing at first load, then, when I visited another page or hard-refreshed, gone again.

I'm not sure what's causing the issue, I suspect caching (the script getting executed only once and then, when the main page is reloaded, not loaded for a reason) but I haven't been able to find a workaround.

**Comment by 4yx** [comment]
I'll include the best I could get to run. This time it stays consistent with page changes, but hard refreshing may still break it.

**Comment by BastelPichi** [comment]
> > The problem is that DOMContentload triggers when the site itself is loaded - not when the site is really loaded(the time where theres this loading circle). That way it cant find the tutorial item and cant change its content.
> 
> That does not seem to be the issue. I tried putting it in the header advertising area (which loads after the loading circle is complete if I'm not mistaken), changed the DOMContentLoaded to a window.AddEventListener('load'), and I tried adding the script directly in the head and body areas. The best result I got was the tutorial link changing at first load, then, when I visited another page or hard-refreshed, gone again.
> 
> I'm not sure what's causing the issue, I suspect caching (the script getting executed only once and then, when the main page is reloaded, not loaded for a reason) but I haven't been able to find a workaround.

Well for me it worked to just add a delay. Best way of course is to update the render list thingy like Hans, but idk

**Comment by 4yx** [comment]
> Well for me it worked to just add a delay.

Oh that is interesting. Does my update work for you, if not, do you think you could contribute the change you made with the delay?

> Best way of course is to update the render list thingy like Hans

There are always better solutions, yes, and I imagine Hans as a much more experienced developer has written a better solution, I do not want to take a look at his code as I don't want to be opened to a copyright infringement. If no other solution works I could look up on how to update a render list and see how to apply that to VistaPanel.

**Comment by BastelPichi** [comment]
vPanel gets rendered from a list called "PAGE.appGroups". You just gotta modify the values. Thats it. Hans has a pretty convenient code for that, but coding your own shouldnt be too hard.

**Comment by BastelPichi** [comment]
vPanel gets rendered from a list called "PAGE.appGroups". You just gotta modify the values. Thats it. Hans has a pretty convenient code for that, but coding your own shouldnt be too hard.

Havent tried the new code yet.

**Comment by 4yx** [comment]
Thanks! It is working sometimes and others not, I tested it myself. Bummer.

> vPanel gets rendered from a list called "PAGE.appGroups". You just gotta modify the values. Thats it. Hans has a pretty convenient code for that, but coding your own shouldnt be too hard.

I know what you're mentioning, I'd seen it before in the source code view. Never tried modifying that. I will.

Reopening the issue as it wasn't fixed at all.

**Comment by BastelPichi** [comment]
Just one more thing. If Ifastnet changes the itemlist, wont that brake? lol...
Ill look into it tmrrow or so

**Comment by 4yx** [comment]
> Just one more thing. If Ifastnet changes the itemlist, wont that brake? lol... Ill look into it tmrrow or so

If iFastNet changes the order of the item list, or the item list itself, I'll make sure to update it. I'll agree it wasn't the best solution, probably, but it was the quickest I could think of. In any case, it should be working as intended, and I doubt iFastNet is going to be updating that list anytime soon.

**Comment by 4yx** [comment]
As a matter of fact, I just updated it in a way that ensures that, as long as the item list remains the same, it will work regardless of order.
