### ISSUE TITLE
"Change Password" and "Change Language" behave differently

### ISSUE THREAD

**Issue by 4yx** [WybeNetwork/VistaPanel-Customizations#22]
While the "Change Password" script alters the link and text of the button in the dropdown, "Change Language" alters the link and text of the item (and icon, which it should not) in the panel's Preferences widget. This is because of a change introduced in 3b5fed271bda1aa1475f337cf9f1cb389d7dcc2b, which altered the way Change Language was working without retaining the old code for the dropdown, and the same change did not occur for Change Password.

The ideal would be, of course, for both scripts to do both, that is, change the links and text in both places. We should also try to figure out what the best way of rewriting Change Language is so that the new text is not inserted into the icon.

Although this could be superseded by our work in #10 (if I manage to find the time to work on such a script, ~~as it would require a huge amount of my time given my inexperience around JS~~ edit: it took me a day), I believe it would be good to update them.

Both scripts will most likely be rewritten by tomorrow, although if anyone has any ideas on how to avoid essentially doing the same work twice (once to replace the dropdown links, and once for the panel widget elements), they would be greatly appreciated.

**Comment by 4yx** [comment]
Since element changer covers the functionality of changing the links in the widgets, I believe both scripts should be altering the name and URL in the dropdown options. Any thoughts on this @mahofficial?

**Comment by 4yx** [comment]
AADev's response from Discord:
> I'll implement a script for changing links and text in that user menu
> and also for adding new items in that menu
If this script is created, both change-password and change-language will become obsolete. They'll be modified to change the URL in the dropdown and eventually dropped.

**Comment by mahofficial** [comment]
After documentation and testing, I'll release that script here. The features it is going to have are:
- Change Link & Name of User nav menu items
- Add new user nav menu item at nth position
- Remove any menu item
