### ISSUE TITLE
Tutorials link is not working.

### ISSUE THREAD

**Issue by NamVr** [WybeNetwork/VistaPanel-Customizations#8]
The title says it all.
I pasted the code in the footer section and the link didn't changed.

**Comment by mahofficial** [comment]
Had you followed this: https://github.com/WybeNetwork/VistaPanel-Customizations/tree/master/tutorial-link-changer#content-type-header-errors
If yes then kindly provide me your website link.

**Comment by NamVr** [comment]
Yes I followed this.
I pasted the code in the footer section in MOFH panel.
I don't know why.

Here's my cPanel: https://cpanel.vhoster.cf
Also I have currently removed this part of code because I inserted the cPanel logo Copyright changer.

PS: I have read about the conflict because both uses **var b**, that's why I have removed the tutorials link code before adding the cPanel logo code. 
The cPanel logo code works fine.

**Comment by mahofficial** [comment]
@NamVr Kindly re-add the code so that I can check.

**Comment by mahofficial** [comment]
@PlanetTheCloud Can you look into the code please :)

**Comment by NamVr** [comment]
> @NamVr Kindly re-add the code so that I can check.
> 
Sure I will add the code. But you said it wont work in the readme file with the cPanel logo. Should I remove the logo script first?

> > Also I have currently removed this part of code because I inserted the cPanel logo Copyright changer.
> 
> You can use multiple vPanel Customizations
How?

> L.E: I Checked that you are using our theme. We don't have CDN anymore but our friend is supporting us. You can use https://millie.vizudev.net/wybenetwork/gradient-blue-lite/styles.css as CDN to use our templates. Work in the same way as old cdn worked.

Wait, is it possible to check without actually having a account in my reseller?

**Comment by NamVr** [comment]
What should I do? @PlanetTheCloud @mahofficial

**Comment by mahofficial** [comment]
> But you said it wont work in the readme file with the cPanel logo

In readme.md it is written that it can be combined with it that mean it can be used without having to use repeatedly "var b ="



> Wait, is it possible to check without actually having a account in my reseller?

Yes, anyone having account on MOFH server can use your vPanel or any other vPanel to login.

**Comment by mahofficial** [comment]
> What should I do? @PlanetTheCloud @mahofficial

Seems like a bug with the script, @PlanetTheCloud can solve but I am trying also to find a solution.

**Comment by NamVr** [comment]
> > But you said it wont work in the readme file with the cPanel logo
> 
> In readme.md it is written that it can be combined with it that mean it can be used without having to use repeatedly "var b ="
> 
> > Wait, is it possible to check without actually having a account in my reseller?
> 
> Yes, anyone having account on MOFH server can use your vPanel or any other vPanel to login.

Ohk. So I should add the code how?

**Comment by mahofficial** [comment]
> > How?
load both scripts .js file and follow documentation for initialization.
(Any script that uses b.name can be combined within one e.g. We have two scripts b.cpanel and b.tutorials then for their initialization we will do
var b = {cpanel: "init value", tutorials: "init value",}
That is what combined mean in readme.md)
The above method shows how you can use multiple scripts.
If any script doesn't have variable b.name then you have to specify its variable differently. For its initialization you can check the readme of that script)

**Comment by NamVr** [comment]
Sorry I could not understand this thing :( That's sad.
I have very little knowledge of JS or php

**Comment by mahofficial** [comment]
> I have very little knowledge of JS or php

Same goes for me lol. I have HTML/CSS knowledge and very little knowledge of JS.
Here is the full code for you to use
`<script type="text/javascript">  

    var b = {  
        tutorial : "YOUR TUTORIAL LINK WITH HTTP PROTOCOL", 
        company_name : "Your company name",  
        company_logo : "Your company logo",  
        company_started : "What year did your company start?",  
        prm_site : "Your Primary site URL (With HTTP:// or HTTPS://)",  
    }  

</script>  
<script src="https://cdn.jsdelivr.net/gh/VPTOfficial/VistaPanel-Customizations/tutorial-link-changer/tutorial-link-changer.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/gh/VPTOfficial/VistaPanel-Customizations/cpanel-logo-to-copyright/cpanel-logo-to-copyright.js" type="text/javascript"></script>`

**Comment by NamVr** [comment]
Probably quoting brokes here :(

**Comment by NamVr** [comment]
Ok should I remove all the codes and then add this in the footer?
`<script type="text/javascript">  

    var b = {  
        tutorial : "YOUR TUTORIAL LINK WITH HTTP PROTOCOL", 
        company_name : "Your company name",  
        company_logo : "Your company logo",  
        company_started : "What year did your company start?",  
        prm_site : "Your Primary site URL (With HTTP:// or HTTPS://)",  
    }  

</script>  
<script src="https://cdn.jsdelivr.net/gh/VPTOfficial/VistaPanel-Customizations/tutorial-link-changer/tutorial-link-changer.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/gh/VPTOfficial/VistaPanel-Customizations/cpanel-logo-to-copyright/cpanel-logo-to-copyright.js" type="text/javascript"></script>`

**Comment by mahofficial** [comment]
> Ok should I remove all the codes and then add this in the footer?

Wait the links need to be updated. They are referring to our old username.

**Comment by NamVr** [comment]
Ok I am paused. Let me know the updated code 🔢

**Comment by mahofficial** [comment]
> Ok I am paused. Let me know the updated code 🔢

Done! 
But Tutorials Link Changer Script still need a fix @PlanetTheCloud

**Comment by NamVr** [comment]
Ok so I am adding this code

> > I have very little knowledge of JS or php
> 
> Same goes for me lol. I have HTML/CSS knowledge and very little knowledge of JS.
> Here is the full code for you to use
> 
> ```js
> <script type="text/javascript">  
> 
>     var b = {  
>         tutorial : "YOUR TUTORIAL LINK WITH HTTP PROTOCOL", 
>         company_name : "Your company name",  
>         company_logo : "Your company logo",  
>         company_started : "What year did your company start?",  
>         prm_site : "Your Primary site URL (With HTTP:// or HTTPS://)",  
>     }  
> 
> </script>  
> <script src="https://cdn.jsdelivr.net/gh/WybeNetwork/VistaPanel-Customizations/tutorial-link-changer/tutorial-link-changer.js" type="text/javascript"></script>
> <script src="https://cdn.jsdelivr.net/gh/WybeNetwork/VistaPanel-Customizations/cpanel-logo-to-copyright/cpanel-logo-to-copyright.js" type="text/javascript"></script>
> ```

**Comment by NamVr** [comment]
Ok I updated the application. Kindly check.
Regards,

`cpanel.vhoster.cf/`

**Comment by NamVr** [comment]
Ok fortunately, the logo is working nicely.
Yet the same issue, the link is not working of tutorials 👎

**Comment by NamVr** [comment]
Ok I will wait for your response and I am here 💯

**Comment by PlanetTheCloud** [comment]
Hi, Issue identified.
iFastNet has updated the cPanel which caused the script to break.

**Comment by NamVr** [comment]
Accha

**Comment by PlanetTheCloud** [comment]
Yes, I am aware that it is vPanel but I'm too used to refer it as cPanel 😁, sorry for that.

**Comment by NamVr** [comment]
Ohk no problem. I understand. xD
Anyways, so the script works now?

**Comment by NamVr** [comment]
Well any updates here? @PlanetTheCloud @mahofficial

**Comment by NamVr** [comment]
Surprizingly after testing, the tutorials link works in Microsoft Edge not in Chrome! @mahofficial @PlanetTheCloud

**Comment by NamVr** [comment]
Ok I got something:

https://stackoverflow.com/questions/4365246/how-to-change-href-of-a-tag-on-button-click-through-javascript
And the html block is:
`<a id="item_cloudflare_analytics" class="itemTextWrapper link" ng-href="http://tutorials.securesignup.net/" ng-attr-target="{{::item.target}}" {{::item.acontent}}="" ng-bind-html="::item.itemdesc" href="http://tutorials.securesignup.net/" target="_blank">Tutorials</a>`

**Comment by PlanetTheCloud** [comment]
Issue fixed. 

> Ok I got something:
> 
> https://stackoverflow.com/questions/4365246/how-to-change-href-of-a-tag-on-button-click-through-javascript
> And the html block is:
> `<a id="item_cloudflare_analytics" class="itemTextWrapper link" ng-href="http://tutorials.securesignup.net/" ng-attr-target="{{::item.target}}" {{::item.acontent}}="" ng-bind-html="::item.itemdesc" href="http://tutorials.securesignup.net/" target="_blank">Tutorials</a>`
> 
> We have got class and id. Is that something we can do? Actually I have never done php or js so sorry if I am posting non-sensical links here :(

Also this is not what we're looking for xD but thanks for trying.

**Comment by NamVr** [comment]
> Issue fixed.
> 
> > Ok I got something:
> > https://stackoverflow.com/questions/4365246/how-to-change-href-of-a-tag-on-button-click-through-javascript
> > And the html block is:
> > `<a id="item_cloudflare_analytics" class="itemTextWrapper link" ng-href="http://tutorials.securesignup.net/" ng-attr-target="{{::item.target}}" {{::item.acontent}}="" ng-bind-html="::item.itemdesc" href="http://tutorials.securesignup.net/" target="_blank">Tutorials</a>`
> > We have got class and id. Is that something we can do? Actually I have never done php or js so sorry if I am posting non-sensical links here :(
> 
> Also this is not what we're looking for xD but thanks for trying.

Your welcome! I am eager to test this now 👍

**Comment by NamVr** [comment]
Probably.
https://cdn.jsdelivr.net/gh/WybeNetwork/VistaPanel-Customizations/tutorial-link-changer/tutorial-link-changer.js

It's not fixed yet here :(

**Comment by NamVr** [comment]
@PlanetTheCloud

**Comment by mahofficial** [comment]
> Probably.
> https://cdn.jsdelivr.net/gh/WybeNetwork/VistaPanel-Customizations/tutorial-link-changer/tutorial-link-changer.js
> 
> It's not fixed yet here :(

I think fixed as it says last modified on 6th august. 
Try hard refresh.

**Comment by NamVr** [comment]
Hard refreshing worked. I don't know why I am becoming damm stupid asking such silly questions.Okay thanks very much!06.08.2020, 21:16, "MAHOfficial" <notifications@github.com>:

Probably.
https://cdn.jsdelivr.net/gh/WybeNetwork/VistaPanel-Customizations/tutorial-link-changer/tutorial-link-changer.js
It's not fixed yet here :(

I think fixed as it says last modified on 6th august.
Try hard refresh.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
 --------------------------------------------------------------------------------- Let me know if we can help you further. We always try to provide customer superior service levels, quickly and accurate at the point. I hope I was able to address your query efficiently. NOTE: We are providing high-quality gaming servers for you at a discounted price during the lockdown. To avail the offer, please visit our website and compare plans. Regards,Naman VratiWordPress Freelancer and Cloud Management Engineer - Founder of Team ELITES Org.https://namanvrati.cf/

**Comment by PlanetTheCloud** [comment]
> Hard refreshing worked. I don't know why I am becoming damm stupid asking such silly questions. Okay thanks very much! Yet, the issue is not solved. This wont work in https!!! @PlanetTheCloud

What do you mean by won't work in https?
Can you provide me the cPanel link?

*In theory, this code should work regardless of the connection type.

**Comment by NamVr** [comment]
Ok wait wait.
I am removing all the codes from my adverts section and let's try again everything.

I need the cPanel Logo replacer, and the links above I mentioned.
I am not removing the dark theme, it is in footer.

Tell me all the code I am starting fresh and let's try again.
The cPanel URL will be: https://cpanel.vhoster.ga/
