### ISSUE TITLE
cPanel Themes - Only Front Page shows dark

### ISSUE THREAD

**Issue by NamVr** [WybeNetwork/VistaPanel-Customizations#9]
Hi Guys!

Thanks for the lot of efforts to make a dark theme I tried using it.
But the theme only worked for the main page of cPanel.

Is there any way that the theme could work for all the sub-pages, like domains, ssl/tls etc?
We just need to include extra css referring to all of the ids and tags.

**Comment by mahofficial** [comment]
You need to add styles file in footer advert area instead of header advert area to make it work on all the pages.

**Comment by NamVr** [comment]
It worked. Thank You!
